name: gosh-workspace
baseUrl: https://httpbin.org
defaultHeaders:
  User-Agent: "gosh/0.1.0"
  Accept: "application/json"
environments:
  dev:
    API_TOKEN: "dev-token-12345"
    API_BASE: "https://dev.example.com"
  prod:
    API_TOKEN: "prod-token-67890"
    API_BASE: "https://api.example.com"
